### ISSUE TITLE
Capitalization difference?

### ISSUE THREAD

**Issue by n8ur** [holgerlembke/MCP47x6#1]
Hi --

Your library uses "MCP47X6.cpp" and "MCP47x6.h" ("X" capitalized differently).  Is there a reason for that?  I'm curious because Windows would ignore the difference but Linux (which I use) wouldn't.

Thanks,
John

**Comment by holgerlembke** [comment]
John,

thanks for the note. Seems like I simply did not note the different spelling and as you said rightly, it didn't make a difference on my Windows box. 

I fixed it: https://github.com/holgerlembke/MCP47x6/commits/master

**Comment by n8ur** [comment]
Thank you for the quick reply and fix.  I was just worried I was missing something.
